### ISSUE TITLE
NFC Graphic and Shipping Date :mobile_phone_off: 

### ISSUE THREAD

**Issue by mangledbottles** [mangledbottles/Fonz-Music-LLC-Client-Web-Application#9]
This graphic is not linked as specified.
![image](https://user-images.githubusercontent.com/22305511/114315695-f6042b00-9af7-11eb-8975-48d9845aed2f.png)

**Comment by mangledbottles** [comment]
![image](https://user-images.githubusercontent.com/22305511/114315810-804c8f00-9af8-11eb-80e5-d133dfe51fcc.png)
This is also outdated

**Comment by diarmuidmcg** [comment]
then change it big dawg
